- menu_name: "لینک‌ها"

- name: "تماس"
  url: "/contact/"
  title: "تماس"

- name: "آراس‌اس"
  url: "/feed.xml"
  title: "آر اس‌ اس"

- name: "فید"
  url: "/atom.xml"
  title: "فید"

- name: "نقشه سایت"
  url: "/sitemap.xml"
  title: "نقشه"
